apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: observer-eye
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: observer-eye-middleware:latest
          imagePullPolicy: Never
          command:
            [
              "celery",
              "-A",
              "telemetry.celery_tasks",
              "worker",
              "--loglevel=info",
              "-Q",
              "metrics,logs,traces,alerts,ml",
            ]
          envFrom:
            - configMapRef:
                name: observer-config
            - secretRef:
                name: observer-secrets
